### ISSUE TITLE
Install and test the data

### ISSUE THREAD

**Issue by Juls777** [gilahwi/ProjectMI#7]
Install and test wiktextract

Download wiktionary (if it is not already installed with wiktextract)

Index it with Solr

**Comment by gilahwi** [comment]
Have you managed to get wiktextract working? I'm having some difficulties with it :/

**Comment by Juls777** [comment]
Hi! not yet, I'll be working at wiktextract this evening. I will write you how it will go)

**Comment by Juls777** [comment]
Well, I also have difficulties with wiktextract... I tried to setup it as it was written here: https://pypi.org/project/wiktextract/#description, but after I write the command 'python3 setup.py install' to taito-shell, I got this error message: 
'/appl/opt/python/3.4.0-gcc-shared/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/appl/opt/python/3.4.0-gcc-shared/lib/python3                           .4/site-packages/test-easy-install-42668.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /appl/opt/python/3.4.0-gcc-shared/lib/python3.4/site-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://pythonhosted.org/setuptools/easy_install.html

Please make the appropriate changes for your system and try again.'

What is wrong in your case?
